struct proc;
void consoleinit(void);
void consoleintr(int c);
int consoleread(uint64 dst, int n);
int consolewrite(uint64 src, int n);
void consputc(int c);
void uartinit(void);
void uartintr(void);
void uartputc_sync(int c);
void plicinit(void);
void plicinithart(void);
int plic_claim(void);
void plic_complete(int irq);
void trapinit(void);
void syscall(void);
uint64 usertrap(void);
void userenter(void) __attribute__((noreturn));
int devintr(void);
struct proc *myproc(void);
int procinit(void);
int proc_fork(void);
void proc_exit(int status) __attribute__((noreturn));
int proc_wait(uint64 status);
int proc_exec(const char *name);
int proc_valid_range(uint64 addr, uint64 len);
void printf(const char *fmt, ...);
void panic(const char *msg) __attribute__((noreturn));
